version: "3"
services:

  postgres-db:
    hostname: postgres
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  oracle-xe-db:
    image: oracleinanutshell/oracle-xe-11g:latest
    container_name: oracle-xe
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      POSTGRES_USER: system
      POSTGRES_PASSWORD: oracle

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mysql'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: